#开发环境配置
server:
  port: 8080
  servlet:
    context-path: /smart

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customdev
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.czy.smart.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback-boot.xml
