#测试环境
server:
  port: 8080
  servlet:
    context-path: /smart

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shirodemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 3000000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  freemarker:
    cache: false
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: req
    prefix:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
#      auto_import: common/common.ftl as com
      template_update_delay: 0
      datetime_format: yyyy-MM-dd
      classic_compatible: true
  mvc:
    static-path-pattern: /static/**

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.czy.smart.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback-boot.xml

